[package]
name = "bevy_bench"
version = "0.1.0"
authors = ["ElliotB256"]
edition = "2018"

[dependencies]
bevy = "0.5"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false